-
  name: Install and start apache 
  hosts: webserver
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root

  tasks:

  - name: install htppd 
    yum: pkg=httpd state=latest 

  - name: write the apache config file 
    template: src=/srv/httpd.j2 dest=/etc/httpd.config

  - name: start httpd
    service: name=httpd state=started
