---

- hosts: webserver
  become: true
  tasks:
    - service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=stopped

- hosts: database
  become: true
  tasks:
    - service: name=mysqld state=stopped
